[package]
name = "passports"
version = "0.1.0"
authors = ["spadix0 <spadix@users.sourceforge.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
regex = "1"
