[package]
name = "shuttle"
version = "0.1.0"
authors = ["spadix0 <spadix@users.sourceforge.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3"
num-integer = "0.1"
num-traits = "0.2"
